#!/bin/bash
# Try to find web root in puphpet config
webroot="/var/www"
if [ -f "puphpet/config.yaml" ]; then
	webrootPuphpet=$(cat puphpet/config.yaml|grep -E "target: /.+?"|cut -d ":" -f 2|cut -d " " -f 2-|grep -oE -m1 "^/.+")
	if [ "$webrootPuphpet" != "" ]; then
		webroot="$webrootPuphpet"
	fi
	serverName=$(cat puphpet/config.yaml|grep servername|cut -d ":" -f 2|cut -d " " -f 2-)
fi

vagrant ssh -c "export XDEBUG_CONFIG=\"phpstorm=awd\" && export PHP_IDE_CONFIG=\"serverName=$serverName\" && cd $webroot && $*" -- -q
